version: '3'
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - fake
    environment:
      - API_URL=http://fake:8080
      - API_KEY
  fake:
    build:
      context: ./fake-api/
    ports: ["8080:8080"]
    environment:
      - API_KEY
    